name: Build and Publish Vue site

on:
  push:
    branches: [ main ]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'andreaswachs'
        reponame: 'andreaswachs.github.io'
        gitemail: 'andreas@wachs.dk'
        gitname: 'andreaswachs'
        gitmsg: 'Deploy Pages app'
        token: ${{ secrets.GITHUB_TOKEN }}

