# This is a basic workflow to help you get started with Actions

name: Index.html rename on push

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  rename_event:
    runs-on: ubuntu-latest
    name: Publish Image  
    steps:
    - if: github.ref == 'refs/heads/gh-pages'
      run: cp index.html 404.html

